AWSTemplateFormatVersion: 2010-09-09

Parameters:

  AvailabilityZone:
    Type: String

  PublicSubnetCidr:
    Type: String

  PrivateSubnetCidr:
    Type: String

  VpcId:
    Type: String

  IgwId:
    Type: String

Resources:

  # Eip:
  #   Type: AWS::EC2::EIP
  #   Properties:
  #     Domain: vpc
  #     Tags:
  #       - Key: Name
  #         Value: !Sub VaultWarden/Eip/${AvailabilityZone}

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W33
            reason: This is a public subnet.
    Properties:
      VpcId: !Ref VpcId
      AvailabilityZone: !Ref AvailabilityZone
      CidrBlock: !Ref PublicSubnetCidr
      MapPublicIpOnLaunch: true
      Tags:
        - Key: subnet-type
          Value: Public
        - Key: Name
          Value: !Sub VaultWarden/PublicSubnet/${AvailabilityZone}

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Sub VaultWarden/PublicRouteTable/${AvailabilityZone}

  RoutePublic:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IgwId

  SubnetRouteTableAssociationPublic:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  # NatGw:
  #   Type: AWS::EC2::NatGateway
  #   Properties:
  #     SubnetId: !Ref PublicSubnet
  #     AllocationId: !GetAtt Eip.AllocationId
  #     Tags:
  #       - Key: Name
  #         Value: !Sub VaultWarden/NatGw/${AvailabilityZone}

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcId
      AvailabilityZone: !Ref AvailabilityZone
      CidrBlock: !Ref PrivateSubnetCidr
      MapPublicIpOnLaunch: false
      Tags:
        - Key: subnet-type
          Value: Private
        - Key: Name
          Value: !Sub VaultWarden/PrivateSubnet/${AvailabilityZone}

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Sub VaultWarden/PrivateRouteTable/${AvailabilityZone}

  RoutePrivate:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IgwId
#      NatGatewayId: !Ref NatGw

  SubnetRouteTableAssociationPrivate:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet
      RouteTableId: !Ref PrivateRouteTable

Outputs:

  PublicSubnetId:
    Value: !Ref PublicSubnet

  PrivateSubnetId:
    Value: !Ref PrivateSubnet
